### ISSUE TITLE
Compilation of tests does not work

### ISSUE THREAD

**Issue by fedochet** [danyaberezun/compiler-workout#1]
When running `./test.sh`, the only thing that is printed is debug information like this: 
```
x=1
Undefined variable a
y=2
z=3
t=4
Undefined variable b
eval s (Binop ("-", Binop ("+", Var ("x"), Binop ("*", Var ("y"), Var ("z"))), Const (3))) = 4
eval s (Binop ("&&", Binop ("+", Binop ("-", Var ("t"), Var ("z")), Var ("y")), Var ("x"))) = 1
```

It looks like invocations of eval from `test000.ml` (and `printf` from them) do not work

OCaml version is `4.04.0`, OS is Ubuntu

**Comment by danyaberezun** [comment]
Да, см. последний commit.

**Comment by fedochet** [comment]
Проблема ушла, спасибо!
