### ISSUE TITLE
HW7

### ISSUE THREAD

**Issue by demiurg906** [danyaberezun/compiler-workout#100]
В заготовке под седьмое дз есть несколько несостыковок:
1. в `Language.ml` нет объяснения тому, что есть `k` в объявлении `Stmt.eval` (и я как-то не очень понимаю, что оно значит
2. в `SM.ml` в заготовке функции `eval` не учтено, что в `Expr.config` появилось возвращаемое значение
3. также, в `SM.ml` отсутсвует байткод `POP`, который необходим в случае, если вызывается функция, которая что-то возвращает, но при этом на call-site это значение нигде не используется (по-моему, по-хорошему, для анализа таких случаев нужно запускать отлельный проход, который для каждого вызова функции проверяет, является ли он частью expression или нет, но в заготовках на это нет и намёка)

**Comment by demiurg906** [comment]
@danyaberezun, и еще один поинт в пользу того, что у функций надо писать типы:
ocaml, не смотря на все заявления о мощной статической типизации, достаточно нелогично выводит типы. Вот, например, функция `env#definition` принимает 4 аргумента, но компилятор выводит сигнатуру метода не в месте его объявления, а в месте первого вызова, из-за чего, если ошибиться в вызове в первый раз, компилятор будет падать на корректных вызовах, что сильно затрудняет поиск ошибок

Также проставление типов легко помогло бы обнаружить проблемы типа второй, что я описал выше

**Comment by xamgore** [comment]
Типовые аннотации к функциям без определений точно нужны, не понимаю, зачем их писать в комментариях.

**Comment by dboulytchev** [comment]
> 2. в `SM.ml` в заготовке функции `eval` не учтено, что в `Expr.config` появилось возвращаемое значение

Исправлено.

По остальному: а Вы были ли на лекции? Совершенно не предполагается, что изучение комментариев в исходном коде заданий достаточно для его выполнения и понимания.

**Comment by dboulytchev** [comment]
> Типовые аннотации к функциям без определений точно нужны, не понимаю, зачем их писать в комментариях.

Потому, что такое описание (вида val что-то) нельзя помещать в тексте структур (реализации модулей). Еще раз, никто не мешает Вам расставить типы так, как Вы считаете нужным, и вообще изменить код по Вашему разумению.

**Comment by xamgore** [comment]
@dboulytchev, типы аргументов можно указывать прямо в let, использовать val не нужно:

```ocaml
let eval (ex : Expr) = ...
```

**Comment by dboulytchev** [comment]
@xamgore, Между указанием типа в `let ...` и использованием `val...` есть существенная разница: пропробуйте откомпилировать следующий фрагмент и объясните результат:

```ocaml
let x : 'a = 3

module T : sig val x : 'a end =
  struct
    let x = 3
  end
```
И еще раз: никто не запрещает Вам расставить типы в `let ...` самостоятельно, если Вам это помогает.

**Comment by demiurg906** [comment]
Ещё у вас `State#push_scope` и `Scope#drop_scope` из шестой домашки магическим образом превратились в `State#enter` и `State#leave`. 

Сколь я понял, эти домашки вы копируете с домашек центра прошлого года. Если вы уж начинаете что-то в них переименовывать, делайте это, пожалуйста, консистентно (или предупреждая о переименованиях, я не знаю, какой из этих двух вариантов исходный)
