### ISSUE TITLE
А выставьте, пожалуйста, оценки в журнал?

### ISSUE THREAD

**Issue by dkhalansky** [danyaberezun/compiler-workout#140]
Туда можно выставлять не только окончательные оценки. Если есть надежда, что у кого-то оценка вырастет, ему пишут ">=3".

**Comment by danyaberezun** [comment]
Что есть журнал?

**Comment by dkhalansky** [comment]
https://docs.google.com/spreadsheets/d/1gMo966EPNxbBigM_Raqsn62v_tkAAKg0rGy_6IOtDNQ/edit#gid=0 вот это.

**Comment by danyaberezun** [comment]
Ну, если за сегодня откроют к ней доступ на редактирования, тогда возможно.
А по поводу ">=3", по-моему, две недели с последнего задания давно прошли... а результаты есть в таблице курса

**Comment by dkhalansky** [comment]
Нам сами кураторы перенесли зачёты. Оказывается, у нас предмет даже не на оценку. Спасибо!
