### ISSUE TITLE
Expressions are not tested on i386?

### ISSUE THREAD

**Issue by sandwwraith** [danyaberezun/compiler-workout#240]
`regression/expressions/Makefile` launches compiler with `-i` and `-s`, but does not launches compiler to compile anything to assembly. What is more strange, it has `rm -f *.s *~ $(TESTS)` in clean, which tries to delete over 10000 unexisting binaries, causing `rm` to fail with 'too much arguments'.

**Comment by danyaberezun** [comment]
Thanks, have to be fixed in hw5
