### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by demiurg906** [danyaberezun/compiler-workout#48]
Есть предложение в ветках с домашками поддерживать акуальное состояние `.gitignore`, чтобы не возникало претензий вида "закоммичено 100500 лог файлов", что происходит из-за плохо настроенного проекта.

Актуальный `.gitignore` для ветки `hw4`:
```
.depend
*.cmi
*.cmx
*.o
*.opt
*.log
!*/orig
*.s
```

**Comment by xamgore** [comment]
Можно коммитить только те файлы, что уже были в индексе с помощью флага `-a` :)

```
git commit -a -m "commit message"
```
