### ISSUE TITLE
Old generated... tests format in hw10

### ISSUE THREAD

**Issue by fresheed** [danyaberezun/compiler-workout#564]
Tests in expressions/ and deep-expressions/ of branch hw10 have old format `read(x)` whereas those in hw9 and hw11 have new (and expected) format of `x := read()`.

**Comment by danyaberezun** [comment]
[fixed](https://github.com/danyaberezun/compiler-workout/commit/ce2be8fe01e4a0de211197c404d4661e9b62ce48)
